"""Postgres-backed OAuth in-flight flow store.

Replaces a Python dict so `/auth/callback` can land on a different
replica than the one that served `/auth/start`. TTL sweep is lazy:
every `pop()` deletes rows older than `ttl_seconds` in the same
transaction, so no background thread is needed.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timedelta, timezone
from pathlib import Path

from google_auth_oauthlib.flow import Flow
from psycopg_pool import ConnectionPool

logger = logging.getLogger(__name__)


# psycopg's prepared-statement path rejects multi-statement execute()
# calls ("cannot insert multiple commands into a prepared statement"),
# so the table + index are two separate statements executed in
# sequence within the same transaction / connection.
CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS oauth_flows (
    state       TEXT PRIMARY KEY,
    flow_json   JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

CREATE_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS oauth_flows_created_at_idx
    ON oauth_flows (created_at)
"""


def ensure_oauth_flows_table(pool: ConnectionPool) -> None:
    """Create the `oauth_flows` table + index if missing. Idempotent.

    Called from `build_services()` right after `PostgresSaver.setup()`
    so the schema is guaranteed present before any `/reauth` request
    hits the store.
    """
    with pool.connection() as conn:
        with conn.cursor() as cur:
            cur.execute(CREATE_TABLE_SQL)
            cur.execute(CREATE_INDEX_SQL)


class OAuthFlowStore:
    """Postgres-backed store for in-flight OAuth `Flow` objects.

    Keyed by CSRF `state` (opaque URL-safe string generated by
    `POST /reauth`). Serializes the minimal reconstructable state
    (scopes, redirect_uri) as JSON; the client secrets file is
    re-read on `pop()` to hydrate a fresh `Flow` — never pickle.
    """

    def __init__(
        self,
        pool: ConnectionPool,
        client_secrets_path: str | Path,
        *,
        ttl_seconds: int = 600,
    ) -> None:
        self._pool = pool
        self._client_secrets_path = str(client_secrets_path)
        self._ttl_seconds = ttl_seconds

    # ---------- serialization ----------

    @staticmethod
    def _serialize(flow: Flow) -> dict:
        # google-auth-oauthlib's Flow exposes scopes / redirect_uri as
        # both public props and private-ish attrs; use the public path.
        # code_verifier is the PKCE nonce populated by authorization_url();
        # we MUST persist it across the pop-put-pop cycle so
        # /auth/callback's fetch_token() sends the same verifier Google
        # is expecting (else Google returns
        # `invalid_grant: Missing code verifier`).
        return {
            "scopes": list(flow.oauth2session.scope or []),
            "redirect_uri": flow.redirect_uri,
            "code_verifier": getattr(flow, "code_verifier", None),
        }

    def _reconstruct(self, state: str, data: dict) -> Flow:
        flow = Flow.from_client_secrets_file(
            self._client_secrets_path,
            scopes=list(data.get("scopes") or []),
            state=state,
            redirect_uri=data["redirect_uri"],
        )
        code_verifier = data.get("code_verifier")
        if code_verifier:
            # google-auth-oauthlib Flow uses this attribute to include
            # the PKCE verifier when exchanging the auth code for tokens.
            flow.code_verifier = code_verifier
        return flow

    # ---------- CRUD ----------

    def put(self, state: str, flow: Flow) -> None:
        payload = json.dumps(self._serialize(flow))
        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "INSERT INTO oauth_flows (state, flow_json) "
                    "VALUES (%s, %s::jsonb) "
                    "ON CONFLICT (state) DO UPDATE SET "
                    "  flow_json = EXCLUDED.flow_json, "
                    "  created_at = now()",
                    (state, payload),
                )

    def pop(self, state: str) -> Flow | None:
        """Fetch + delete the flow for `state`. Returns None if
        missing or expired. Also opportunistically sweeps any rows
        older than `ttl_seconds` in the same transaction."""
        cutoff = datetime.now(timezone.utc) - timedelta(seconds=self._ttl_seconds)
        with self._pool.connection() as conn:
            with conn.cursor() as cur:
                # Lazy TTL sweep — one small DELETE per pop.
                cur.execute(
                    "DELETE FROM oauth_flows WHERE created_at < %s",
                    (cutoff,),
                )
                # Fetch-and-delete the target only if still fresh.
                cur.execute(
                    "DELETE FROM oauth_flows "
                    "WHERE state = %s AND created_at >= %s "
                    "RETURNING flow_json",
                    (state, cutoff),
                )
                row = cur.fetchone()
        if row is None:
            return None
        payload = _extract_flow_json(row)
        if payload is None:
            logger.warning(
                f"oauth_flow_store.pop({state!r}) returned a row with "
                "no flow_json — treating as miss"
            )
            return None
        return self._reconstruct(state, payload)


def _extract_flow_json(row: object) -> dict | None:
    """Row-factory-agnostic access to the `flow_json` column value."""
    if isinstance(row, dict):
        value = row.get("flow_json")
    elif isinstance(row, (list, tuple)) and row:
        value = row[0]
    else:
        value = None
    if value is None:
        return None
    # psycopg returns JSONB as parsed Python object; defend against
    # a hypothetical driver upgrade that returns str.
    if isinstance(value, str):
        return json.loads(value)
    return value
